[theme]
primaryColor = "#8e6100ff"                # Color for buttons, sliders, and links
backgroundColor = "#d0d0d0ff"             # Main background color
secondaryBackgroundColor = "#a4a4a4ff"    # Sidebar and widget backgrounds
textColor = "#171717ff"                   # Text color
font = "sans serif"                       # Options: "sans serif", "serif", or "monospace"